---
apiVersion: v1
kind: Template
metadata:
  annotations:
    description: "This is Nepthys CronJob Config"
    openshift.io/display-name: "Nepthys CronJob"
    tags: "thoth,ai-stacks,nepthys"
    template.openshift.io/documentation-url: "https://github.com/thoth-station/nepthys/"
    template.openshift.io/long-description: "This is Nepthys used for automatic package releases and updates."
    template.openshift.io/provider-display-name: "Red Hat, Inc."
    version: "1.0.0"
  labels:
    app: thoth
    component: nepthys
    template: nepthys-cronjob
  name: nepthys-cronjob

objects:
  - apiVersion: batch/v1beta1
    kind: CronJob
    metadata:
      labels:
        app: thoth
        component: nepthys
      name: nepthys
    spec:
      concurrencyPolicy: Forbid
      failedJobsHistoryLimit: 1
      jobTemplate:
        spec:
          template:
            metadata:
              labels:
                app: thoth
                component: nepthys
            spec:
              containers:
                - image: nepthys-job
                  name: nepthys
                  resources:
                    limits:
                      cpu: 500m
                      memory: 1Gi
                    requests:
                      cpu: 500m
                      memory: 1Gi
                  volumeMounts:
                    - mountPath: /home/user/.ssh
                      name: ssh-config
                  env:
                    - name: PIPENV_NOSPIN
                      value: "1"
                    - name: PIPENV_COLORBLIND
                      value: "1"
                    - name: PIPENV_COLORBLIND
                      value: "1"
                    - name: PIPENV_HIDE_EMOJIS
                      value: "1"
                    - name: GITHUB_TOKEN
                      valueFrom:
                        secretKeyRef:
                          key: github-oauth-token
                          name: nepthys-secret
                    - name: GITHUB_USER
                      valueFrom:
                        secretKeyRef:
                          key: user-name
                          name: nepthys-secret
                    - name: GITHUB_USER_EMAIL
                      valueFrom:
                        secretKeyRef:
                          key: user-email
                          name: nepthys-secret
              restartPolicy: Never
              volumes:
                - name: ssh-config
                  secret:
                    items:
                      - key: ssh-privatekey
                        mode: 384
                        path: id_rsa
                    secretName: nepthys-secret
      schedule: "@daily"
      successfulJobsHistoryLimit: 2
      suspend: false
