---
apiVersion: v1
kind: Template
metadata:
  annotations:
    description: "This is Nepthys Secret Config"
    openshift.io/display-name: "Nepthys Secret"
    tags: "thoth,ai-stacks,nepthys"
    template.openshift.io/documentation-url: "https://github.com/thoth-station/nepthys/"
    template.openshift.io/long-description: "This is Nepthys used for automatic package releases and updates."
    template.openshift.io/provider-display-name: "Red Hat, Inc."
    version: "1.0.0"
  labels:
    app: thoth
    component: nepthys
    template: nepthys-secret
  name: nepthys-secret

objects:
  - apiVersion: v1
    kind: Secret
    metadata:
      labels:
        app: thoth
        component: nepthys
      name: nepthys-secret
    stringData:
      ssh-privatekey: "${NEPTHYS_SSH_PRIVATE_KEY}"

parameters:
  - description: "Using SSH private key to authenticate the public key set in GitHub."
    displayName: "SSH Private Key"
    name: NEPTHYS_SSH_PRIVATE_KEY
    required: true
