FROM fedora:28
#RUN yum install -y epel-release
RUN yum install -y \
      gcc \
      python3-devel \
      python3-pip
RUN pip3 install \
      ipython==5.0.0 \
      jupyter==1.0.0 \
      jupyter-client==5.2.3 \
      jupyter-console==5.2.0 \
      jupyter-core==4.4.0 \
      matplotlib==2.1.2 \
      nbconvert==5.3.1 \
      pandas==0.22.0 \
      papermill==0.13.4 \
      ipykernel==4.8.2
